name: OliveTin
version: "1"
slug: olivetin
description: A home assistant OliveTin integration
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
options: {}
schema: {}
