name: OliveTin
version: "1.0.0"
slug: olivetin
description: A home assistant OliveTin integration
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8000/tcp: 8000
options:
  server: "http://myserver:1337/api/"
schema:
  server: str
